name: asan_testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the module
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'tests/requirements.txt'

      - name: Start Kafka
        uses: ybyzek/cp-all-in-one-action@v0.2.1
        with:
          type: cp-all-in-one-community

      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt

      - name: Build module
        run: |
          export MAKEFLAGS=-j8
          export CC=clang
          export CXX=clang++
          git clone https://github.com/tarantool/tarantool
          cd tarantool
          git checkout release/2.11
          export LSAN_OPTIONS=suppressions=${PWD}/asan/lsan.supp
          cmake . -DENABLE_ASAN=ON -DENABLE_DIST=ON
          make -j16
          sudo make install
          cd ..
          tarantoolctl rocks STATIC_BUILD=ON ENABLE_ASAN=ON make

      - name: Run tarantool application
        run: |
          export TT_LOG=tarantool.log
          export LSAN_OPTIONS=suppressions=${PWD}/tarantool/asan/lsan.supp
          tarantool tests/app.lua > output.log 2>&1 &

      - name: Run test
        run: KAFKA_HOST=localhost:9092 pytest tests

      - name: Print Tarantool logs
        if: always()
        run: |
          cat tarantool.log
          cat output.log
